service: aws-lambda-emsdm-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    MONGO_URI: MONGO_URI="mongodb+srv://emdsm-user:emdsmjgmo@emdsm-db.pnszqsz.mongodb.net/"

functions:
  test:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get

  createCourse:
    handler: src/course/addCourse.addCourse
    events:
      - httpApi:
          path: /course
          method: post
  
  getCourses:
    handler: src/course/getCourses.getCourses
    events:
      - httpApi:
          path: /course/all
          method: get
  
  getCourse:
    handler: src/course/getCourse.getCourse
    events:
      - httpApi:
          path: /course/find/{id}
          method: get

  updateCourse:
    handler: src/course/updateCourse.updateCourse
    events:
      - httpApi:
          path: /course/find/{id}
          method: put

  deleteCourse:
    handler: src/course/deleteCourse.deleteCourse
    events:
      - httpApi:
          path: /course/find/{id}
          method: delete

  loginUser:
    handler: src/user/loginUser.loginUser
    events:
      - httpApi:
          path: /user/login
          method: post

  registerUser:
    handler: src/user/registerUser.registerUser
    events:
      - httpApi:
          path: /user/register
          method: post

  getUserRol:
    handler: src/user/getUserRol.getUserRol
    events:
      - httpApi:
          path: /user/{rol}
          method: get

  getPublicUser:
    handler: src/user/getPublicUser.getPublicUser
    events:
      - httpApi:
          path: /user/public/{mySearch}
          method: get

  getStudentsByCourse:
    handler: src/user/getStudentsByCourse.getStudentsByCourse
    events:
      - httpApi:
          path: /user/course/{courseId}
          method: get

  getCountUsers:
    handler: src/user/getCountUsers.getCountUsers
    events:
      - httpApi:
          path: /user/count
          method: get
  
  addInstructorUser:
    handler: src/user/addInstructorUser.addInstructorUser
    events:
      - httpApi:
          path: /user/instructor
          method: post
  
  addStudentUser:
    handler: src/user/addStudentUser.addStudentUser
    events:
      - httpApi:
          path: /user/student
          method: post
  
  editUser:
    handler: src/user/editUser.editUser
    events:
      - httpApi:
          path: /user/update
          method: post
  
  deleteUser:
    handler: src/user/deleteUser.deleteUser
    events:
      - httpApi:
          path: /user/delete
          method: post

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    basePath: ./

       
